flaskclub/clubs/forms.py
from flask_wtf import FlaskForm 
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, PasswordField, SubmitField, BooleanField, SelectField, TextAreaField
from wtforms.validators import DataRequired, Length, ValidationError, Email 
from flaskclub.models import Clubs


class JoinForm(FlaskForm):
	submit = SubmitField('Join') 
	edit = SubmitField('Add Activity') 
	delete = SubmitField('Delete Activity')


class ActivityForm(FlaskForm):
	title = StringField('Activity Name', validators=[DataRequired(), Length(min=2)]) 
	picture = FileField('Insert Image', validators=[FileAllowed(['jpg', 'png'])])
	add = SubmitField('Add Activity') 


class NewClubForm(FlaskForm):
	id =  StringField('Club ID', validators=[DataRequired(), Length(min=1)]) 
	name = StringField('Club Name', validators=[DataRequired(), Length(min=2)]) 
	acronym = StringField('Acronym', validators=[DataRequired(), Length(min=2)]) 
	contact = StringField('Contact', validators=[DataRequired(), Length(min=2)]) 
	picture = FileField('Insert Image', validators=[FileAllowed(['jpg', 'png'])]) 
	email = StringField('Email', validators=[DataRequired(), Email()]) 
	add = SubmitField('Add Club')  

	def validate_id(self, id):
		club_id = Clubs.query.filter_by(id=id.data).first()

		if club_id: 
			raise ValidationError('Club ID is already registered.') 

flaskclub/forum/forms.py
from flask_wtf import FlaskForm 
from wtforms import StringField, PasswordField, SubmitField, BooleanField, SelectField, TextAreaField
from wtforms.validators import DataRequired, ValidationError

class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')

class ReplyForm(FlaskForm):
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')

flaskclub/clubs/routes.py
import secrets, os, datetime
from flask import render_template, flash, redirect, url_for, abort, request, Blueprint
from flaskclub import app, db, bcrypt
from flaskclub.clubs.forms import JoinForm, ActivityForm, NewClubForm
from flaskclub.models import Clubs, Activities, person, Student
from flask_login import login_user, current_user, logout_user, login_required
from flaskclub.clubs.utils import save_picture, save_picture_club


clubs = Blueprint('clubs', __name__)

@clubs.route("/clubs", methods=['GET','POST'])
def all_clubs(): 

	all_clubs = Clubs.query.all()
	return render_template('clubs.html', title='Clubs', clubs=all_clubs)

@clubs.route("/club/<int:club_id>", methods=['GET','POST'])
def club_detail(club_id): 
	page = request.args.get('page', 1, type=int)

	form = JoinForm() 
	club = Clubs.query.get_or_404(club_id) 
	all_activities = Activities.query.order_by(Activities.date_posted.desc()).paginate(page=page, per_page = 4)

	if form.validate_on_submit(): 
		if (current_user.is_authenticated) and (current_user.role != 'admin') :	
			user = Student.query.filter_by(id=current_user.id).first()
			user.club_id = club_id  
			user.role = 'member'

			flash('You have joined this club!', 'success') 
			
			db.create_all()
			club.people.append(current_user)
			db.session.commit()

			return redirect(url_for('clubs.club_detail', club_id=club_id)) 
		else: 
			flash('You need to Log In first.', 'danger') 
			return redirect(url_for('clubs.club_detail', club_id=club_id)) 

	return render_template('details.html', title=club.name, club=club, activities=all_activities, form=form)


@clubs.route("/<int:club_id>/add_activity", methods=['GET','POST']) 
@login_required 
def add_activity(club_id):
	form = ActivityForm()
	club = Clubs.query.get_or_404(club_id) 


	if (current_user.role != 'member') or (current_user.role != ''): 
		if form.validate_on_submit(): 
			if form.picture.data: 
				picture_file = save_picture(form.picture.data)
				activity = Activities(name=form.title.data, club_id=club_id, image_file=picture_file, date_posted=datetime.date.today()) 
				
				db.session.add(activity)
				db.session.commit()

				flash('Activity Posted!', 'success') 

				return redirect(url_for('clubs.club_detail', club_id=club_id)) 
			else: 
				flash('Error', 'danger') 
				return redirect(url_for('clubs.add_activity', club_id=club_id)) 

	return render_template('add_activity.html', title=club.name, form=form, club=club)

@clubs.route("/delete_activity/<int:activity_id>", methods=['GET','POST']) 
@login_required 
def delete_activity(activity_id):

	if (current_user.role != 'member') or (current_user.role != ''): 
		Activities.query.filter_by(id=activity_id).delete()

		db.session.commit()
		flash('Activity Deleted!', 'success') 

		return redirect(url_for('clubs.club_detail', club_id=current_user.club_id)) 
			
	else: 
		print(form.errors)
		flash('Error', 'danger')
		return redirect(url_for('clubs.club_detail', club_id=current_user.club_id)) 

	return redirect(url_for('clubs.club_detail', club_id=current_user.club_id)) 

@clubs.route("/new_club", methods=['GET','POST']) 
@login_required 
def new_club(): 
	form = NewClubForm() 
	all_clubs = db.session.query(Clubs).count()

	

	if (current_user.role == 'admin') : 
		if form.validate_on_submit(): 
			if form.picture.data: 
				picture_file = save_picture_club(form.picture.data)
				club = Clubs(name=form.name.data, id=form.id.data, image_file=picture_file, contact=form.contact.data, email=form.email.data, acronym=form.acronym.data) 
				
				# return redirect(url_for('users.dashboard', role=current_user.role)) 
			else: 
				club = Clubs(name=form.name.data, id=form.id.data, contact=form.contact.data, email=form.email.data, acronym=form.acronym.data) 
	

			db.session.add(club)
			db.session.commit()
			flash('Club Added!', 'success') 
			return redirect(url_for('users.dashboard', role=current_user.role)) 
			

	
	return render_template('add_club.html', title="New Club", form=form, clubs=all_clubs)

@clubs.route("/delete_club/<int:club_id>", methods=['GET','POST']) 
@login_required 
def delete_club(club_id):

	if (current_user.role == 'admin'): 
		Clubs.query.filter_by(id=club_id).delete()

		db.session.commit()
		flash('Club Deleted!', 'success') 

		return redirect(url_for('clubs.all_clubs')) 
			
	else: 
		print(form.errors)
		flash('Error', 'danger')
		return redirect(url_for('clubs.club_detail', club_id=club_id)) 

	return redirect(url_for('clubs.club_detail', club_id=club_id)) 

flaskclub/forum/routes.py
import datetime
from flask import render_template, flash, redirect, url_for, abort, request, Blueprint
from flaskclub import app, db, bcrypt
from flaskclub.forum.forms import PostForm, ReplyForm
from flaskclub.models import person, Post, Reply
from flask_login import login_user, current_user, logout_user, login_required
forum = Blueprint('forum', __name__)


@forum.route("/forums")
def forums():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page = 6) 
    

    return render_template('forums.html', posts=posts)

@forum.route("/post/<int:post_id>", methods=['GET','POST'])
def post(post_id):

    post = Post.query.get_or_404(post_id) 
    replies = Reply.query.filter_by(post_id=post_id)

    return render_template('post.html', title=post.title, post=post, replies=replies)

@forum.route("/add_post", methods=['GET','POST']) 
@login_required 
def add_post():
	form = PostForm()

	if form.validate_on_submit():
	    post = Post(title=form.title.data, content=form.content.data, author=current_user)
	    db.session.add(post)
	    db.session.commit()
	    flash('Post has been created!', 'success')
	    return redirect(url_for('forum.forums'))

	return render_template('add_post.html', title='Add Post', form=form, legend="New Post")

@forum.route("/<int:post_id>/add_reply", methods=['GET','POST']) 
@login_required 
def add_reply(post_id):
	form = ReplyForm()

	if form.validate_on_submit():
	    reply = Reply(content=form.content.data, user_id=current_user.id, post_id=post_id, author=current_user)
	    db.session.add(reply)
	    db.session.commit()
	    flash('Reply has been posted!', 'success')
	    return redirect(url_for('forum.post', post_id=post_id))

	return render_template('add_reply.html', title='Post A Reply', form=form, legend="New Reply")

@forum.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()

    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Your post has been updated!', 'success')
        return redirect(url_for('forum.post', post_id=post.id))

    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('add_post.html', title='Update Post',
                           form=form, legend='Update Post')

@forum.route("/post/<int:post_id>/delete", methods=['POST', 'GET'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted', 'success')
    return redirect(url_for('forum.forums'))

flaskclub/main/routes.py
from flask import render_template, flash, redirect, url_for, Blueprint, abort, request
from flaskclub import app, db, bcrypt
from flaskclub.models import Activities
from flask_login import login_user, current_user, logout_user, login_required

main = Blueprint('main', __name__)


@main.route("/")
@main.route("/home")
def home():
	page = request.args.get('page', 1, type=int)
	activities = Activities.query.paginate(page=page, per_page = 6)

	return render_template('home.html', activities=activities)

flaskclub/users/routes.py
from flask import render_template, flash, redirect, url_for, Blueprint, request, jsonify
from flaskclub import app, db, bcrypt
from flaskclub.users.forms import RegistrationForm, LoginForm, RolesForm, UpdateAccountForm
from flaskclub.models import Student, BinusID, Clubs, Admin
from flask_login import login_user, current_user, logout_user, login_required
from flaskclub.users.utils import save_picture_profile

users = Blueprint('users', __name__)




@users.route("/register", methods=['GET','POST'])
def register():
	# if current_user.is_authenticated:
	# 	return redirect(url_for('home'))
	form = RegistrationForm() 

	if form.validate_on_submit(): 
		user_id = BinusID.query.filter_by(id=form.student_id.data).first()
		if user_id: 
			
			
			hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
			user = Student(firstname=form.firstname.data, lastname=form.lastname.data, email=form.email.data, password=hashed_password, gender=form.gender.data, batch=form.batch.data, id=form.student_id.data)
			user_id.email=form.email.data 

			db.session.add(user)
			db.session.commit()
			

			flash('Account Created!', 'success')
			return redirect(url_for('users.login')) 
	# else:
	# 	flash('Please fill the data required for registration correctly.', 'danger')

	return render_template('register.html', title='Register', form=form)

@users.route("/login", methods=['GET','POST'])
def login():
	if current_user.is_authenticated:
		return redirect(url_for('main.home'))
	form = LoginForm()

	if form.validate_on_submit(): 
	
		user = Student.query.filter_by(email=form.email.data).first()

		if user and bcrypt.check_password_hash(user.password, form.password.data):
			login_user(user, remember=form.remember.data)
			return redirect(url_for('main.home'))
		else:
			flash('Incorrect email or password entered.', 'danger')

	return render_template('login.html', title='Login', form=form)

@users.route("/logout")
def logout():
	logout_user()
	return redirect(url_for('main.home'))

@users.route("/profile/<id>", methods=['GET', 'POST'])
def profile(id):	
	club = Clubs.query.all() 
	student = Student.query.get_or_404(id)
	myclub = Clubs.query.get_or_404(student.club_id) 
	
	return render_template('profile.html', title='Profile', myclub=myclub, student=student, club=club) 

@users.route("/<int:club_id>/edit_roles", methods=['GET','POST'])
@login_required
def edit_roles(club_id):
	form = RolesForm()
	club = Clubs.query.get_or_404(club_id) 


	if (current_user.role == 'president') or (current_user.role == 'admin') : 
		if form.validate_on_submit():  
			user = Student.query.filter_by(id=form.student_id.data).first() 
			for club in user.clubs:  
				if club.id == club_id: 
					user.role = form.roles.data
					user.club_id = club_id

					db.session.commit()

					flash('Role has been changed.', 'success') 

					return redirect(url_for('users.edit_roles', club_id=club_id))
			flash('User is not in this club', 'danger') 
			return redirect(url_for('users.edit_roles', club_id=club_id)) 

	else: 
		print(form.errors)
		flash('You are not permitted', 'danger') 
		return redirect(url_for('main.home')) 

	return render_template('edit_roles.html', title="Edit Roles", form=form, club=club)

@users.route("/update_profile/<id>", methods=['GET','POST']) 
@login_required 
def change_image(id):
	form = UpdateAccountForm()

	if current_user.is_authenticated:
		if form.validate_on_submit(): 
			if form.picture.data: 
				picture_file = save_picture_profile(form.picture.data)
				current_user.image_file = picture_file
				
				db.session.commit()

				flash('Image Updated!', 'success') 

				return redirect(url_for('users.profile', id=id)) 
			else: 
				flash('Error', 'danger') 
				return redirect(url_for('users.change_image', id=id)) 

	return render_template('update_profile.html', title="Profile", form=form) 

@users.route("/update_profile/delete/<id>", methods=['POST', 'GET'])
@login_required
def delete_picture(id): 
	if current_user.is_authenticated: 
		if current_user.image_file != 'default.jpg':
			if current_user.id == id: 
				current_user.image_file = 'default.jpg'

				db.session.commit()
				flash('Picture removed.', 'success')
				return redirect(url_for('users.profile', id=id))
		else:
			flash('Picture removed.', 'success')
			return redirect(url_for('users.change_image', id=id)) 

@users.route("/<role>/dashboard", methods=['GET', 'POST']) 
@login_required 
def dashboard(role):
	
	return render_template('dashboard.html') 

flaskclub/templates/add_activity.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section w-50 p-3" style="margin:0 auto">
    <form method="POST" action="" enctype="multipart/form-data"> 
        {{ form.hidden_tag() }}
        <img class="img-fluid " height="200px" width="200px" src="{{ url_for('static', filename='club_image/' + club.image_file) }}" style="margin-right:auto;margin-left:auto;display:block;width:40%">
        <!-- <h1 class="display-3" style="display:inline;">{{ club.name }}</h2> -->
        <fieldset class="form-group">

            <legend class="border-bottom mb-4">{{ legend }}</legend>

            <div class="form-group"> 
                 <h1 class="display-8">Add An Activity</h2>
                {{ form.title.label(class="form-control-label") }}
                {% if form.title.errors %}
                    {{ form.title(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.title.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.title(class="form-control form-control-lg") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.picture.label() }}
            {{ form.picture(class="form-control-file") }}
            {% if form.picture.errors %}
                {% for error in form.picture.errors %}
                    <span class="text-danger"> {{error}} </span> <br>
                {% endfor %}
            {% endif %}
        </div> 

        <div class="form-group">
            {{ form.add(class="btn btn-outline-info") }}
        </div>
    </form>
</div>


{% endblock content %}

flaskclub/templates/add_club.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section w-50 p-3" style="margin:0 auto">
    <form method="POST" action="" enctype="multipart/form-data"> 
        {{ form.hidden_tag() }}
        
        <fieldset class="form-group">

            <legend class="border-bottom mb-4">{{ legend }}</legend>


            <div class="form-group"> 
                 <h1 class="display-8">Add A Club</h2>
                 	<br>
                 <div class="form-group">
                 {{ form.id.label(class="form-control-label") }}
				{% if form.id.errors %}
					{{ form.id(class="form-control form-control-lg is-invalid")}}
					<div class = "invalid-feedback">
						{% for error in form.id.errors %}
							<span> {{error}} ---- There are {{ clubs }} clubs registered </span>
						{% endfor %}
					</div>

				{% else %}
					{{ form.id(class="form-control form-control-lg") }}

				{% endif %}
				</div>
				<div class="form-group">
                {{ form.name.label(class="form-control-label") }}
                {% if form.name.errors %}
                    {{ form.name(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.name.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.name(class="form-control form-control-lg") }}
                {% endif %}
                </div>
                <div class="form-group">
                {{ form.acronym.label(class="form-control-label") }}
                {% if form.acronym.errors %}
                    {{ form.acronym(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.acronym.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.acronym(class="form-control form-control-lg") }}
                {% endif %}
                </div>
                <div class="form-group">
                {{ form.email.label(class="form-control-label") }}
				{% if form.email.errors %}
					{{ form.email(class="form-control form-control-lg is-invalid")}}
					<div class = "invalid-feedback">
						{% for error in form.email.errors %}
							<span> {{error}} </span>
						{% endfor %}
					</div>

				{% else %}
					{{ form.email(class="form-control form-control-lg") }}

				{% endif %}
				</div>
				<div class="form-group">
				{{ form.contact.label(class="form-control-label") }}
				{% if form.contact.errors %}
					{{ form.contact(class="form-control form-control-lg is-invalid")}}
					<div class = "invalid-feedback">
						{% for error in form.contact.errors %}
							<span> {{error}} </span>
						{% endfor %}
					</div>

				{% else %}
					{{ form.contact(class="form-control form-control-lg") }}

				{% endif %}
				</div>
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.picture.label() }}
            {{ form.picture(class="form-control-file") }}
            {% if form.picture.errors %}
                {% for error in form.picture.errors %}
                    <span class="text-danger"> {{error}} </span> <br>
                {% endfor %}
            {% endif %}
        </div> 

        <div class="text-center">
            {{ form.add(class="btn btn-outline-info") }}
        </div>
    </form>
</div>


{% endblock content %}

flaskclub/templates/clubs.html
{% extends "layout.html" %}
{% block content %}
<br>
<br>
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				{% for club in clubs %} 
					<a href="{{ url_for('clubs.club_detail', club_id=club.id) }}" style="color:black">  
					<img class="img-fluid" height="170px" width="170px" src="{{ url_for('static', filename='club_image/' + club.image_file) }}" style="margin: 15px 15px 15px 15px"></a> 	
				{% endfor %}
			</div>
		</div>
	</div>
{% endblock content %}

flaskclub/templates/dashboard.html
{% extends "layout.html" %}
{% block content %}
	<div>
		<h1 class="display-5 text-center" style="font-family: Roboto Slab;font-size:60px ">Dashboard</h1>
		<br>
		
		<!-- <button type="button" class="btn btn-primary btn-sm" style="margin-left:25px;margin-bottom:40px;">New Post</button> -->
		
	</div>   
        <article class="media content-section w-50" style="margin:0 auto;margin-bottom:20px">        
        	<a class="btn btn-info" href="{{ url_for('clubs.new_club')}}" role="button" style="margin-top:20px;margin-bottom:40px;width:200px;margin-left:auto;margin-right:auto">New Club</a>  
        </article>
    
{% endblock content %}

flaskclub/templates/forums.html
{% extends "layout.html" %}
{% block content %}
	<div>
		<h1 class="display-5" style="margin-left:25px;font-family: Roboto Slab">Forums</h1>
		<br>
		
		<a class="btn btn-info" href="{{ url_for('forum.add_post')}}" role="button" style="margin-left:25px;margin-bottom:40px;heght:200px;width:200px;float:right;">New Post</a>	
		<!-- <button type="button" class="btn btn-primary btn-sm" style="margin-left:25px;margin-bottom:40px;">New Post</button> -->
		
	</div> 


    
        <article class="media content-section w-95">
          
          <div class="media-body">
          	{% for post in posts.items %}
          	<div class = "content-section w-25 p-1" style="margin:0 auto;margin-bottom:20px">
	            <div class="article-metadata">
                <img class="rounded-circle img-fluid" height="25px" width="25px" src="{{ url_for('static', filename='profile_picture/' + post.author.image_file) }}" style="margin-right:0px">
	              <a class="mr-2" href="#" style="color:black">{{ post.author.firstname }} {{post.author.lastname}}</a>
	              <small class="text-muted">{{ post.date_posted }}</small>
	            </div>
	            <p><a class="article-title" href="{{ url_for('forum.post', post_id=post.id) }}">{{ post.title }}</a></p>
          	</div>
          	{% endfor %}
          </div> 

          
        </article>
        <div class="col text-right">
              {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
                {% if page_num %}
                  {% if posts.page == page_num %}
                    <a class="btn btn-info mb-4" href="{{ url_for('forum.forums', page=page_num) }}" style=>{{ page_num }}</a>
                  {% else %}
                    <a class="btn btn-outline-info mb-4" href="{{ url_for('forum.forums', page=page_num) }}">{{ page_num }}</a>
                  {% endif %}
                {% else %}
                  ...
                {% endif %}
              {% endfor %}
            </div>
    
{% endblock content %}

flaskclub/templates/layout.html
<!DOCTYPE html>
<html>
<head>
	<!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='custom.css') }}">
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@577&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Sriracha&display=swap" rel="stylesheet">

    
	{% if title %}
		<title>Binusian Club - {{ title }}</title>
	{% else %}
		<title>Binusian Club</title>
	{% endif %}
</head>

<body>
	<header class="site-header">
	  <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
	  	<h1 ><a href="{{ url_for('main.home') }}" style="color:white;text-decoration:none;font-family:Sriracha">BinusianClubs</a></h1>
	    <div class="container">
	      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
	        <span class="navbar-toggler-icon"></span>
	      </button>
	      <div class="collapse navbar-collapse" id="navbarToggle">
	        <div class="navbar-nav mr-auto">
	          <a class="nav-item nav-link" href="{{url_for('main.home')}}">Home</a>
	          <a class="nav-item nav-link" href="{{url_for('clubs.all_clubs')}}">Clubs</a>
	          <a class="nav-item nav-link" href="{{url_for('forum.forums')}}">Forums</a>
	        </div>
	        <!-- Navbar Right Side -->
	        <div class="navbar-nav">
	        	{% if current_user.is_authenticated %} 
	        		<a href="{{ url_for('users.profile', id=current_user.id) }}" style="color:black"><img class="rounded-circle img-fluid" height="45px" width="45px" src="{{ url_for('static', filename='profile_picture/' + current_user.image_file) }}" style="margin-right:0px"></a> 
	        		 <li class="nav-item dropdown">
				        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
				          {{current_user.firstname}}
				        </a>
				        <div class="dropdown-menu" aria-labelledby="navbarDropdown">

				          <a class="nav-item nav-link" href="{{url_for('users.profile', id=current_user.id)}}" style="color:black">My Profile</a>
				          {% if current_user.role == 'admin' %} 
				          	<a class="nav-item nav-link" href="{{url_for('users.dashboard', role=current_user.role)}}" style="color:brown">Admin Dashboard</a>
				          {% endif %}
				          <a class="nav-item nav-link" href="{{url_for('users.logout')}}" style="color:red">Logout</a>

				          
				        </div>
				      </li>
	        		
	        		

	        	{% else %}
	          		<a class="nav-item nav-link" href="{{url_for('users.login')}}">Login</a>
	          		<a class="nav-item nav-link" href="{{url_for('users.register')}}">Register</a>
	          	{% endif %}
	        </div>
	      </div>
	    </div>
	  </nav>
  </header>

	<main role="main" class="container">
	  <div class="row">
	    <div class="col-md-8">
	    	{% with messages = get_flashed_messages(with_categories=true) %}
	    		{% if messages %}
	    			{% for category, message in messages %}
	    				<div class="alert alert-{{ category }}">
	    					{{ message }}
	    				</div>
	    			{% endfor %}
	    		{% endif %}
	    	{% endwith %}
	    </div>
	  </div>
	</main>
   {% block content %}{% endblock %}


	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

flaskclub/templates/update_profile.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section w-50 p-3" style="margin:0 auto">
    <form method="POST" action="" enctype="multipart/form-data"> 
        {{ form.hidden_tag() }}
        <img class="img-fluid " height="200px" width="200px" src="{{ url_for('static', filename='profile_picture/' + current_user.image_file) }}" style="margin-right:auto;margin-left:auto;display:block;width:40%"> 

        <a class="btn btn-danger" href="{{ url_for('users.delete_picture', id=current_user.id) }}" role="button" style="margin-left:25px;margin-bottom:40px;width:150px;float:right;">Remove Picture</a>  
       
        <fieldset class="form-group">

            <legend class="border-bottom mb-4">{{ legend }}</legend>

        <div class="form-group" >
            {{ form.picture.label() }}
            {{ form.picture(class="form-control-file") }}
            {% if form.picture.errors %}
                {% for error in form.picture.errors %}
                    <span class="text-danger"> {{error}} </span> <br>
                {% endfor %}
            {% endif %}
        </div> 

        <div class="form-group" style="float:center">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>


{% endblock content %}